#!/bin/sh

# Lint js files.

# We only lint files from the custom themes and modules.
include='^src/.*\.js$'
exclude=' '

# The linter path is relative to the root of the repository.
relative=1
linter="node_modules/.bin/eslint"
options="--config .eslintrc --no-eslintrc"
message='Linting JS files...'

# Load and execute the linting code.
. "$(dirname "$0")/lint-common"
